# Generated by Django 5.1 on 2024-08-25 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_name', models.CharField(max_length=100)),
                ('idea_description', models.TextField(blank=True, null=True)),
                ('idea_image', models.ImageField(blank=True, null=True, upload_to='media/idea')),
                ('idea_datetime', models.DateTimeField(auto_now_add=True)),
                ('key_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
