# Generated by Django 5.1 on 2024-09-03 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INEapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='idea_good',
            field=models.ManyToManyField(related_name='good', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_start',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_user', models.BooleanField(default=False)),
                ('image_profile', models.ImageField(upload_to='media/profile')),
                ('data_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_idea', models.CharField(max_length=155)),
                ('sub_body', models.TextField()),
                ('sub_image', models.ImageField(blank=True, null=True, upload_to='media/sub_idea')),
                ('sub_file', models.FileField(blank=True, null=True, upload_to='media/document')),
                ('sub_datetime', models.DateField(auto_now_add=True)),
                ('key_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INEapp.idea')),
            ],
        ),
    ]
