# Generated by Django 5.1 on 2024-09-03 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INEapp', '0002_idea_idea_good_idea_idea_start_datauser_subidea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_good',
            field=models.ManyToManyField(blank=True, related_name='good', to=settings.AUTH_USER_MODEL),
        ),
    ]
