# Generated by Django 5.1 on 2024-09-11 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INEapp', '0003_alter_datauser_image_profile_alter_idea_idea_good'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datauser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subidea',
            name='sub_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subidea',
            name='sub_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
